name: Run tests

on:
  push:
    branches-ignore: [ release ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.147.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run PostgreSQL
      run: docker-compose -f up --detach
    - name: Run tests
      run: |
        bundle install
        sleep 10
        TEST_COVERAGE=true bundle exec ./bin/test_all_ar_versions
